### ISSUE TITLE
log scores with zero probability should return -Inf, not empty/missing value

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#119]
Currently, I think it returns an empty cell. See screenshot of CSV file from impetus project:
![image](https://user-images.githubusercontent.com/1280767/51441831-e2184880-1ca3-11e9-939a-4101ecfb8e3c.png)

**Comment by matthewcornell** [comment]
@nickreich I see the blank entries for log_single and log_multi - are you saying that blank is OK? I had somewhere that -Inf is (more) correct. Is this issue not an issue? :-)

**Comment by matthewcornell** [comment]
The CSV's blank scores are because there is no saved score for that combination of model+timezero+location+target. That in turn happens in two cases: 1) no truth was found, and 2) no predicted value was found. I need to dig into the code more deeply, but that's what it looks like right now.

**Comment by nickreich** [comment]
That is not a completely satisfying answer to me, because the other scores are there, so there must be a predicted value and truth value, otherwise, how are you calculating, e.g. `abs_error`?

**Comment by nickreich** [comment]
I wonder if this is related to the issue where we are dropping rows with zero probability values? Based on the characteristics of these scores, it looks to me like these are cases where the true values are associated with rows in the forecast that have a zero probability assigned to them, which we would be dropping from our storage...

**Comment by matthewcornell** [comment]
Question: This issue's title suggests not correctly handling zero probability as the cause, but that's not the case here. In this case (blank cells for Impetus), we figured out on 2/11 that the problem is some forecasts do not have a log score (not that the probability is zero). This is in turn caused by the log score not accounting for omitted zero bins that contain the true value (these are optimized out - see #84 ). This means the CSV generation code currently sees a None for the score in these cases, and outputs a blank cell.

Beyond adding support for those missing zero bins (which should fix the empty cell problem), we do have log score code that implements the logic: "clip Math.log(0) to -999 instead of its real value (-Infinity)" from: https://github.com/reichlab/flusight/wiki/Scoring#2-log-score-single-bin . So I think we are handling that case.

**Comment by nickreich** [comment]
This sounds right to me, @matthewcornell . I think the key here is to support the situation where we have dropped the rows and figure out how to calculate/infer the appropriate probabilities. 

For the `log-score (single bin)` metric, I think if the bin associated with truth is missing we can assume that it is zero and just assign the value as coded.

For the `log-score (multi bin)` metric, it is a bit more complicated because you might have the truth bin missing but a bin just on either side of the truth might not be missing.

**Comment by matthewcornell** [comment]
I've coded a fix for the missing zero bins so that the csv has no blank cells, but your comment about the `log-score (multi bin)` metric makes me think the calculation as written is wrong. I only add up existing bins, not accounting for zero ones that might have been excluded. But suppose the true bin has W missing empty bins before and after it. Shouldn't the score use those (all zeros), instead of the non-zero ones that I currently use?

**Comment by nickreich** [comment]
Yes, that is correct. the calculation should account for missing bins.

Also, related to a comment above, I'd prefer to have `-Inf` values instead of `-999` for `log-score` values that have zero probability. Would that be workable?

**Comment by matthewcornell** [comment]
OK, I wasn't sure whether the databases we use would support symbolic infinity values, but I verified they do. The catch is that, due to the underlying python float lib, the value that actually comes out as csv is '-inf' -- note the case. Q: How important to you is using the '-Inf' case as you asked? The argument for keeping the default ('-inf') is that it's expected with Python programs. But I suspect your case ('-Inf') is an R standard?

**Comment by matthewcornell** [comment]
BTW when viewing the csv in Excel the value '-inf' shows as '#NAME'. the row in question is:
```gam_lag1_tops3,2017-04-23,2017,TH02,3_biweek_ahead,37.0,37.0,-inf,-0.003004509020298613,1.0```
See the screen shot, which also shows we no longer have blank cells.

**Comment by matthewcornell** [comment]
(Per slack w/nick we will stay with -999.)
