### ISSUE TITLE
add "Team name" field to Model metadata

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#120]
Could we add a "team name" to the metadata for each model? It should be optional. At the top of each model page, the title of the page should read then:
"Model: [team name] - [model name]"

Would this be metadata bloat? I think it would be useful to have this additional identifier, but we could also code it directly in the model name as needed...

**Comment by matthewcornell** [comment]
Good idea. Right now there's a team name for ensemble models, but it's not a field, it's just included in the description as found in metadata.txt .

Would it be a simple text field? (Rather than creating some kind of more involved Team feature where Users could be associated with Teams, Teams could own ForecastModels, etc.)

**Comment by nickreich** [comment]
Yes, I was thinking of just a simple, optional plain text field that would be associated with each model. No additional "teams" feature (although that might be a reasonable thing to think about down the road).

**Comment by matthewcornell** [comment]
For the Impetus model _gam_lag1_tops3_ ( https://reichlab-forecast-repository.herokuapp.com/model/5 ), what would you like for the team name?

**Comment by nickreich** [comment]
Impetus

-- 
Nicholas G. Reich, Ph.D.
Associate Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.io/
on twitter: @reichlab
