### ISSUE TITLE
Upload retroactive forecasts to Zoltar

### ISSUE THREAD

**Issue by katiehouse3** [reichlab/forecast-repository#170]
As part of this, to get scoring to work we need to fix a discrepancy in timezeros between the truth file I generated from Abhinav's script and the timezeros manually added to the project. The latter is one day later than the former:

- truths-2010-through-2019.csv: https://gist.github.com/matthewcornell/689668f0c713ba796b06534a72fe3768
  scroll down to 20171022
- project timezeros (as of 2019-11-07): https://gist.github.com/matthewcornell/6612815cccebf3be68f3eabbd9389d11
  start at 20171023

His script is here: https://gist.github.com/lepisma/f7b92d7eadd19d1384834ed32af5d53a

**Comment by nickreich** [comment]
I'm happy to help get to the bottom of this, especially as the details of how we have actually determined ground truth have been ever so slightly modified in the past months. so I'd like to have a hand in writing and verifying the code that is creating the ground truth. As I understand it, this shouldn't hold up uploading the actual forecast files, right? We have an updated version of the truth-creation code already for the ensemble work that I will adapt.
@katiehouse3 can you verify some information for me:
 - I don't see the project where this truth file will belong. I think maybe you just haven't created it yet. once you create it, can you send me the link and if possible, give me permissions so that I can add the truth file?
 - when you are creating the timezeroes for this new retrospective CDC flu forecasts project, can we follow the same convention that @Khoale1096 followed in the Real Time CDC Forecasts project? This is that we set the timezero to be the MONDAY of the epidemic week (EW) for which the forecasts were made.

**Comment by katiehouse3** [comment]
@nickreich Here are some clarifications:

- The project has not been created yet because I need to add the correct timezeros to the json template file before making the project. I am currently working on a script to do this. 
- Yes will follow the same convention as @Khoale1096 

Here are my todos in order. Let me know if this looks good!
- [ ] reformat json with correct timezeros
- [ ] create retrospective forecast project
- [ ] fix discrepancy in truths
- [ ] upload the forecasts

**Comment by nickreich** [comment]
I think you can reorder the todos so that you upload forecasts before the truths are in. It is looking actually a bit more complicated than I had first thought, but I'd rather hold off on uploading the truths until we get it right. I don't think this needs to hold up the uploading of forecasts, though.
