### ISSUE TITLE
Forecast uploads become progressively slower

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#176]
Per @Khoale1096 's report.
Q: related?: [Reduce time to download forecasts #148]

**Comment by Khoale1096** [comment]
Closing this issue because zoltpy now has the function util.upload_forecast_batch() which resolves inefficiencies when uploading multiple forecasts within a model, thus increasing the upload speed.

A similar inspection might need to be made for zoltR, once the transfer to zoltar 2 is finished and the zoltR functions are updated
