### ISSUE TITLE
Create an endpoint on Zoltar to return the source field from all forecasts in a project

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/forecast-repository#311]
In relates to validated.json db sync issue reichlab/covid19-forecast-hub#3378, we would like to have an endpoint where we can query the source field of all forecasts in the project.

Documentation regarding the issue and its solution can be accessed [here](https://docs.google.com/document/d/197rRtFNrY3VXrKVueF95hA1PRa8LZ43tw8nKTExrtWE/edit?usp=sharing)

Only the latest versions are to be returned.

**Comment by matthewcornell** [comment]
An update after having the current scheme cause a few days of trouble (see [this slack thread](https://app.slack.com/client/T089JRGMA/unreads/thread/C04EMC7G00P-1679360185.746049)).

Plan:
- Decide where in each Forecast to store each upload's checksum:
    - `notes`: make the entire note be the checksum, e.g., "b66c171b82d3d55e31382a9a1ff6f5df"
    - `source`: encode the checksum in the source, which is currently the filename. e.g., change it to something like "2020-03-30-IHME-CurveFit.csv|b66c171b82d3d55e31382a9a1ff6f5df"
- Change existing endpoint to return either notes or source (currently it returns source, but is easily changed).
- Change upload_covid19_forecasts_to_zoltar.py to first download above endpoint and then use it instead of zoltar_scripts/validated_file_db.json . I'll need to handle authentication/authorization and maybe download format issues.
