### ISSUE TITLE
Integrate FluSight D3 component into Zoltar

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#53]
Add the component at http://flusightnetwork.io/ to Zoltar, prioritizing the features in this order:

1. time chart          } FluSight component
2. scores              } done in Zoltar
2. distribution chart  } FluSight component
4. map                 } FluSight component (maybe)

**Comment by matthewcornell** [comment]
Here's what I know that's left:

1. Y axis domain: The component's y domain config variable is currently hard-coded to 13. But this isn't general. The "CDC Flu challenge (2016-2017)" project only goes up to ~3% on the Y axis. How should I set this on a per-project basis? One approach is to let the user specify in each project's configuration.

2. Y axis title: Steve said the "y-axis should be “DHF cases” or something like that". Same issue as #1, i.e., store in proj config?

3. X axis title: Currently hard-coded to 'Epi week'. Recall that our standard for loading files is to extract the time_zero from the filename. But does that time_zero always represent an EW?

4. Season start EW: Currently the season start EW is hard-coded to 30. From my code:
     # This number is the internal reichlab standard: "We used week 30. I don't think this is a standardized concept outside
     # of our lab though. We use separate concepts for a "season" and a "year". So, e.g. the "2016/2017 season" starts with
     # EW30-2016 and ends with EW29-2017."
   Should this also be project-dependent?

5. Biweeks vs. EWs: How should this be handled differently, say the CDC Flu Challenge vs. Impetus?

6. Model abbreviations: Currently each model's id, which is shown in the legend and the popup, is simply the first 10 chars followed by the internal model id, an int. Is this OK? The order matches the list of models above, so it's unambiguous in a sense. However, Flusight uses the model_abbr field from metadata.txt. Since that metadata is CDC project-specific, I'd have to add an abbreviation field to every model. Is doing so worth it?

7. pointType: The component's pointType config variable is hard-coded to 'mmwr-week', but can also be 'regular-week'. Which is correct for zoltar? Or again, project-specific?

8. Light green line (actual): Should I be showing this? To do so, I believe I need to implement: [Generalize truth values to a table #60]

9. Performance: The visualization page sometimes times out ('Application Error') at the 30 second mark, depending on how warmed up the Heroku Postgres database is. I need to implement an asynchronus message queue to post-process and store this offline whenever there's a change, and then modify the code to use the stored value. A big job.

**Comment by lepisma** [comment]
1. This is _very_ visualization specific. I don't know if keeping this in zoltar's project config makes sense. Maybe we can do something smart on figuring out the domain in foresight itself?
2. Project specific config seems fine here since a project needs to tell what its predicting.
3. Keeping this in config also feels fine to me (again) because having a little text about the time axis in project's metadata makes sense.
4. If we standardize a `time point` (see the next point) in some ways, then we can also ask (for each project) a function (or definition of some sort) that maps the time point to a season. And the other way around, where it takes in a season and returns a slice of time points.

5. From foresight's point of view, I defined each time point as *some object* which
   1. maps to a real date/time object (like mmwr-week to date-time), and
   2. provides a string representation (like `30` for `{ week: 30, year: 2023 }` mmwr-week) for axis tick labels

   Going this route means asking each project to give us these two functions. I don't know if this is a right thing to put in project config since there are at least 2 languages (python, js) needing these functions. We can maybe keep the definition in a language agnostic way and then translate them or something?

6. _

7. For dengue project, we need a `biweek` type. Adding this type would mean adding the two functions mentioned above for this in either foresight itself or asking the user for them. In the first case, we will need to keep just the time point type in each project's config. In the second, we will need to save the functions too. I don't know which looks fine. From a library point of view, I would like to keep the functions outside d3-foresight but that would make the zoltar's config messy. I could make an `extra` module in d3-foresight with all these transformation functions though.

**Comment by matthewcornell** [comment]
_Update to above based on this doc: Zoltar Truth Tables: https://docs.google.com/document/d/1QlgOIST5joBTf-1fzemeVdF_-w8U1-pE17b9KODEhO8/edit#_

1. Think how to detrmine from data. Q: Extend flusight or figure out in Zoltar?

2. Add "target_to_week_unit" to Project.config_dict, e.g.,

CONFIG_DICT = {

    "target_to_week_increment": {
        "-1_biweek_ahead": 1,
        "0_biweek_ahead": 2,
        "1_biweek_ahead": 3,
        "2_biweek_ahead": 4,
        "3_biweek_ahead": 5
    },
    "target_to_week_unit": "DHF cases",  # units for "target_to_week_increment". used to label y-axis of D3 Flusight component

    "time_interval_type": "biweek",
    "time_interval_season_start": 14,

}

3. Add "time_interval_type" to Project.config_dict - see above.

4. Add "time_interval_season_start" to Project.config_dict - see above.

5. See "time_interval_type" above.

6. DEC: leave as-is

7. Use "time_interval_type" above.

8. Yes, will be available when [Generalize truth values to a table · Issue #60] is done - https://github.com/reichlab/forecast-repository/issues/60
